#!/usr/bin/env python3
"""Index skills/agent-dispatcher/roles/*.md into the router, the per-role commands, the
perpetual-mode hook, and the README table.

The role files are the source of truth — hand-edit them, or drop in a new one. This script
never writes them.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent
SKILL = ROOT / "skills" / "agent-dispatcher"
ROLES = SKILL / "roles"
CMDS = ROOT / "commands"
HOOKS = ROOT / "hooks"
SKILL_DIR = "~/.claude/skills/agent-dispatcher"

# Category order in the README. A role must declare one of these.
CATEGORIES = ["Core", "Engineering", "Product & Design", "Knowledge & Business"]


def parse(path):
    """Read one role file's frontmatter. Flat `key: value`, optionally double-quoted."""
    text = path.read_text()
    m = re.match(r"\A---\n(.*?)\n---\n", text, re.S)
    if not m:
        raise SystemExit(f"{path}: missing frontmatter")
    role = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        k, sep, v = line.partition(":")
        if not sep:
            raise SystemExit(f"{path}: frontmatter line is not `key: value` (wrapped?): {line!r}")
        v = v.strip()
        if not v:
            raise SystemExit(f"{path}: frontmatter key '{k.strip()}' has no value")
        role[k.strip()] = v[1:-1] if len(v) > 1 and v[0] == v[-1] == '"' else v
    missing = {"id", "slug", "name", "category", "summary", "use_when", "not_for", "tags"} - set(role)
    if missing:
        raise SystemExit(f"{path}: frontmatter missing {sorted(missing)}")
    if role["category"] not in CATEGORIES:
        raise SystemExit(f"{path}: unknown category {role['category']!r} — one of {CATEGORIES}")
    if role["id"] != path.stem:
        raise SystemExit(f"{path}: id '{role['id']}' does not match the filename")
    role["tags"] = [t.strip() for t in role["tags"].split(",") if t.strip()]
    return role


def load():
    roles = sorted((parse(p) for p in ROLES.glob("*.md")), key=lambda r: r["name"])
    for key in ("id", "slug"):
        seen = {}
        for r in roles:
            if r[key] in seen:
                raise SystemExit(f"duplicate {key} '{r[key]}': {seen[r[key]]} and {r['id']}")
            seen[r[key]] = r["id"]
    if not roles:
        raise SystemExit(f"no role files found in {ROLES} — refusing to build an empty pack")
    return roles


def write_skill(roles):
    rows = "\n".join(
        f"### `{r['id']}` — {r['name']}\n{r['summary']}\n"
        f"- **Route here when:** {r['use_when']}\n"
        f"- **Not for:** {r['not_for']}\n"
        f"- **Signals:** {', '.join(r['tags'])}\n"
        for r in roles)
    tmpl = (ROOT / "SKILL.template.md").read_text()
    (SKILL / "SKILL.md").write_text(
        tmpl.replace("{{ROLES}}", rows).replace("{{COUNT}}", str(len(roles))))


def write_commands(roles):
    CMDS.mkdir(parents=True, exist_ok=True)
    for old in CMDS.glob("agent-*.md"):
        old.unlink()
    for r in roles:
        (CMDS / f"agent-{r['slug']}.md").write_text(
            f"---\ndescription: \"Work as the {r['name']} agent — {r['summary']}\"\n"
            f"argument-hint: \"[task]\"\n---\n\n"
            f"Read the agent-dispatcher skill's `roles/{r['id']}.md` and work as that role for this "
            f"request and the ones that follow, until the user picks another role or says to stop.\n\n"
            f"It sits next to that skill's SKILL.md — `~/.claude/skills/agent-dispatcher/roles/"
            f"{r['id']}.md` for a manual install, or inside the plugin's own directory if it was "
            f"installed as a plugin. Glob for `**/agent-dispatcher/roles/{r['id']}.md` if neither "
            f"path is there.\n\n"
            f"Announce it in one line (`\u2192 {r['id']}`), then do the work. Follow the role's "
            f"working method, deliverable, definition of done, boundaries, and tool posture, scaled "
            f"to the size of the task. The role never overrides harness rules, permissions, or the "
            f"user's explicit instructions.\n\n"
            f"This is a forced role: do the work as asked rather than re-routing or chaining. If "
            f"another specialist would materially change the answer, say so in one line and keep "
            f"going.\n\n$ARGUMENTS\n")


def write_hook(roles):
    HOOKS.mkdir(parents=True, exist_ok=True)
    index = "\n".join(f"- `{r['id']}` — {r['use_when']}\n    not for: {r['not_for']}" for r in roles)
    hook = HOOKS / "agent-dispatcher-activate.sh"
    hook.write_text(f"""#!/bin/bash
# Perpetual agent-dispatcher mode. Armed by ~/.claude/.agent-dispatcher-active, disarmed by
# deleting that file; silenced for one session by ~/.claude/.agent-dispatcher-off/<session_id>
# and for one project by <cwd>/.agent-dispatcher-off. Generated by build.py — edit the
# generator, not this file.
D="${{CLAUDE_CONFIG_DIR:-$HOME/.claude}}"
[ -f "$D/.agent-dispatcher-active" ] || exit 0

# Session ids are uuids, so a sed capture is exact. The payload's cwd can carry JSON escapes,
# so $PWD (the project the session started in) is checked alongside it rather than trusted to it.
payload=$(cat 2>/dev/null)
sid=$(printf '%s' "$payload" | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\\([-0-9a-zA-Z_]*\\)".*/\\1/p')
cwd=$(printf '%s' "$payload" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')

# where this pack is installed: next to this hook (plugin) or under the config dir (manual)
self=$(cd "$(dirname "$0")" && pwd)
if [ -d "$self/../skills/agent-dispatcher/roles" ]; then
  pack=$(cd "$self/../skills/agent-dispatcher" && pwd)
else
  pack="$D/skills/agent-dispatcher"
fi
[ -n "$sid" ] && [ -f "$D/.agent-dispatcher-off/$sid" ] && exit 0
[ -n "$cwd" ] && [ -f "$cwd/.agent-dispatcher-off" ] && exit 0
[ -f "$PWD/.agent-dispatcher-off" ] && exit 0
# forget session silences older than a week
[ -d "$D/.agent-dispatcher-off" ] && find "$D/.agent-dispatcher-off" -type f -mtime +7 -delete 2>/dev/null

printf 'AGENT DISPATCHER ACTIVE (perpetual mode) — this pack lives at %s\n\n' "$pack"
cat <<'DISPATCH'

Route each request that involves real work to the best-fit specialist role below, then work as that
role. Match the "not for" line as carefully as the "route here when" line.
Read PACK/roles/<id>.md before acting as one; read PACK/SKILL.md for the full catalog, the
chaining rules, or to break a tie.

A slash command or an installed skill that covers the request owns the turn: load it, work inside
its procedure, keep the role as posture only, and skip the role announcement.

Announce each role on its own line (-> reviewer) and re-route when the kind of work changes.
Chain roles inside a turn when the work needs it (planner -> implementer -> tester), meeting each
role's definition of done before switching; three per turn is the ceiling. Stop at the deliverable
the user asked for, and scale the deliverable to the task. A plain question, a typo fix, a rename, a
one-line edit: answer or do it, no role and no announcement. A role sets how you work; it never
overrides harness rules, permissions, or the user's explicit instructions.
The user can force a role at any time (/agent-<role>, "stay in tester") - honor it, keep it for the
requests that follow, and do not route or chain out of it until they name another role or say stop.
DISPATCH

if [ -n "$sid" ]; then
  printf 'To stop routing: this session only, run\n  mkdir -p "%s/.agent-dispatcher-off" && touch "%s/.agent-dispatcher-off/%s"\n' "$D" "$D" "$sid"
else
  printf 'To stop routing this session, ask the user for the session id first (the payload carried none).\n'
fi
printf 'For this project, touch .agent-dispatcher-off in its root; everywhere, rm -f "%s/.agent-dispatcher-active".\n\n' "$D"

cat <<'DISPATCH'
ROLES
{index}
DISPATCH
""")
    hook.chmod(0o755)

    (HOOKS / "hooks.json").write_text(
        '{\n  "hooks": {\n    "SessionStart": [\n      {\n'
        '        "matcher": "startup|resume|clear|compact",\n        "hooks": [\n          {\n'
        '            "type": "command",\n'
        '            "command": "bash \\"${CLAUDE_PLUGIN_ROOT}/hooks/agent-dispatcher-activate.sh\\"",\n'
        '            "timeout": 5\n          }\n        ]\n      }\n    ]\n  }\n}\n')


def write_readme(roles):
    readme = ROOT / "README.md"
    if not readme.exists():
        return
    txt = readme.read_text()
    a, b = "<!-- roles:start -->", "<!-- roles:end -->"
    if a not in txt or b not in txt:
        return
    out = []
    for cat in CATEGORIES:
        rows = [r for r in roles if r["category"] == cat]
        if not rows:
            continue
        out += [f"### {cat}", "", "| Command | Role | What it does |", "| --- | --- | --- |"]
        out += [f"| `/agent-{r['slug']}` | {r['name']} | {r['summary']} |" for r in rows]
        out += [""]
    readme.write_text(txt[:txt.index(a) + len(a)] + "\n\n" + "\n".join(out) + txt[txt.index(b):])


def main():
    roles = load()
    write_skill(roles)
    write_commands(roles)
    write_hook(roles)
    write_readme(roles)
    print(f"indexed {len(roles)} roles -> SKILL.md, {len(roles)} commands, hook, README")
    return roles


if __name__ == "__main__":
    main()
