#!/bin/bash
# Perpetual agent-dispatcher mode.
#   arm everywhere:    ~/.claude/.agent-dispatcher-active
#   arm one project:   <project>/.agent-dispatcher-on
#   silence a session: ~/.claude/.agent-dispatcher-off/<session_id>
#   silence a project: <project>/.agent-dispatcher-off   (silencing beats arming)
# Generated by build.py from sources/shared/HOOK.template.sh — edit the template, not this file.
D="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"

# Session ids are uuids, so a sed capture is exact. The payload's cwd can carry JSON escapes,
# so $PWD (the project the session started in) is checked alongside it rather than trusted to it.
payload=$(cat 2>/dev/null)
sid=$(printf '%s' "$payload" | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\([-0-9a-zA-Z_]*\)".*/\1/p')
cwd=$(printf '%s' "$payload" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')

# where this pack is installed: next to this hook (plugin) or under the config dir (manual)
self=$(cd "$(dirname "$0")" && pwd)
if [ -d "$self/../skills/agent-dispatcher/roles" ]; then
  pack=$(cd "$self/../skills/agent-dispatcher" && pwd)
else
  pack="$D/skills/agent-dispatcher"
fi
# silenced? one session, then one project — checked against the payload cwd and the real one
[ -n "$sid" ] && [ -f "$D/.agent-dispatcher-off/$sid" ] && exit 0
[ -n "$cwd" ] && [ -f "$cwd/.agent-dispatcher-off" ] && exit 0
[ -f "$PWD/.agent-dispatcher-off" ] && exit 0

# armed? globally by ~/.claude/.agent-dispatcher-active, or per project by ./.agent-dispatcher-on
# A project arms itself only if the user allow-listed it. Silencing stays repo-local because it
# can only ever reduce behaviour; arming from a cloned repo would not be the user's choice.
armed=""
[ -f "$D/.agent-dispatcher-active" ] && armed=1
for p in "$cwd" "$PWD"; do
  [ -n "$p" ] && [ -f "$p/.agent-dispatcher-on" ]     && [ -f "$D/.agent-dispatcher-projects" ]     && grep -qxF "$p" "$D/.agent-dispatcher-projects" && armed=1
done
[ -n "$armed" ] || exit 0
# forget session silences older than a week
[ -d "$D/.agent-dispatcher-off" ] && find "$D/.agent-dispatcher-off" -type f -mtime +7 -delete 2>/dev/null

printf 'AGENT DISPATCHER ACTIVE (perpetual mode) — this pack lives at %s\n\n' "$pack"
cat <<'DISPATCH'
Read PACK/SKILL.md for direct/guided/coordinated profiles and controls. Simple unambiguous,
low-risk tasks use the direct path with native checks and no extra role/helper/preference reads.
Forced roles and explicitly requested workflows retain their required guidance. Honor forced-role persistence,
user instructions, host permissions and disabled skills. For substantial workspace tasks,
select the role then run python3 -B PACK/context.py --project PROJECT --task-file - --role ID
--compact --map-maintain --json as the first discretionary workspace action: before listings, searches,
contract/source reads, tests or task-file writes. Mandatory host instructions are exempt.
Pass the full unchanged task on quoted stdin. Preserve returned exclusion_policy in later reads.
The helper gates cache writes; add --map-preview for edit limits it may miss. Consume supplied role/guide bodies and excerpts
without rereading; use exact resources paths only for needed missing bodies. Multi-file bugs,
architecture and source-backed documentation qualify even in small projects. Controls,
trivial work, one obvious known-file change and no-workspace tasks bypass the helper.
Use targeted reads if unavailable. Read PACK/CONTEXT.md only for details or inspection.
Default role tie-breaks: plans -> planner; reviews -> reviewer; repository questions without
an artifact -> explorer; source-backed documentation/report updates -> documentation-writer;
clear implementation changes -> implementer. Honor specialist exclusions and justified exceptions.
For guided/coordinated work consume the selected role before substantive work. No broad guide globs or full indexes.
Guided/coordinated activity names role, guides actually read and tools/MCPs selected with progress.
ACTIVITY.md owns style controls; DELEGATION.md owns chaining and independent subagent work.
Never route or chain out of a forced role; a plan request ends with a plan. Same-session
review is a self-check. Missing capabilities do not authorize installation or invented checks.
Run read-only validators inline using python3 -B - with quoted stdin. Do not save temporary
scripts or task text beside the project or in shared /tmp. Necessary permitted scratch copies
use owned temporary-directory contexts; verify removal and report failed/unknown cleanup.

DISPATCH

if [ -n "$sid" ]; then
  printf 'The user stops this with /agent-dispatcher off (or "stop the dispatcher") - never\nhand them a command to run. When they ask, run the line for the scope they meant:\n  this session    mkdir -p "%s/.agent-dispatcher-off" && touch "%s/.agent-dispatcher-off/%s"\n' "$D" "$D" "$sid"
else
  printf 'The user stops this with /agent-dispatcher off. Stopping just this session needs the\nsession id, which this payload did not carry - ask for it, or use a wider scope below.\n'
fi
printf '  this project    touch .agent-dispatcher-off   (beats any arming, including global)\n  everywhere      rm -f "%s/.agent-dispatcher-active"\nEither way, drop the role immediately; the flags only stop the hook re-arming you later.\n/agent-dispatcher status reports what is armed.\n\n' "$D"

cat <<'DISPATCH'
ROLES
{{ROLES}}
DISPATCH
